<a href="https://colab.research.google.com/github/Pritam1729/RECOMMENDER-SYSTEM/blob/main/Recommandation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
!wget -O moviedataset.zip https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%205/data/moviedataset.zip
print('unziping ...')

!unzip -o -j moviedataset.zip 

--2022-06-09 10:08:33--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%205/data/moviedataset.zip
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.45.118.108
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.45.118.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 160301210 (153M) [application/zip]
Saving to: ‘moviedataset.zip’

moviedataset.zip    100%[===================>] 152.88M  33.7MB/s    in 4.5s    

2022-06-09 10:08:38 (33.7 MB/s) - ‘moviedataset.zip’ saved [160301210/160301210]

unziping ...
Archive:  moviedataset.zip
  inflating: links.csv               
  inflating: movies.csv              
  inflating: ratings.csv             
  inflating: README.txt              
  inflating: tags.csv        

In [114]:
#Dataframe manipulation library
import pandas as pd
#Math functions, we'll only need the sqrt function so let's import only that
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [116]:
#Storing the movie information into a pandas dataframe
movies_df = pd.read_csv('movies.csv')
#Storing the user information into a pandas dataframe
ratings_df = pd.read_csv('ratings.csv')
#Head is a function that gets the first N rows of a dataframe. N's default is 5.
movies_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [117]:
#Using regular expressions to find a year stored between parentheses
#We specify the parantheses so we don't conflict with movies that have years in their titles
movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)
#Removing the parentheses
movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)
#Removing the years from the 'title' column
movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')
#Applying the strip function to get rid of any ending whitespace characters that may have appeared
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
#movies_df.head()
display(movies_df)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  import sys


movieId                        title  \
0            1                    Toy Story   
1            2                      Jumanji   
2            3             Grumpier Old Men   
3            4            Waiting to Exhale   
4            5  Father of the Bride Part II   
...        ...                          ...   
34203   151697                   Grand Slam   
34204   151701                   Bloodmoney   
34205   151703         The Butterfly Circus   
34206   151709                         Zero   
34207   151711        The 2000 Year Old Man   

                                            genres  year  
0      Adventure|Animation|Children|Comedy|Fantasy  1995  
1                       Adventure|Children|Fantasy  1995  
2                                   Comedy|Romance  1995  
3                             Comedy|Drama|Romance  1995  
4                                           Comedy  1995  
...                                            ...   ...  
34203                                     Thriller  1967  
34204                           (no genres listed)  2010  
34205                                        Drama  2009  
34206                                 Drama|Sci-Fi  2015  
34207                           (no genres listed)  1975  

[34208 rows x 4 columns]

In [118]:
#Every genre is separated by a | so we simply have to call the split function on |
movies_df['genres'] = movies_df.genres.str.split('|')
movies_df.head()


movieId                        title  \
0        1                    Toy Story   
1        2                      Jumanji   
2        3             Grumpier Old Men   
3        4            Waiting to Exhale   
4        5  Father of the Bride Part II   

                                              genres  year  
0  [Adventure, Animation, Children, Comedy, Fantasy]  1995  
1                     [Adventure, Children, Fantasy]  1995  
2                                  [Comedy, Romance]  1995  
3                           [Comedy, Drama, Romance]  1995  
4                                           [Comedy]  1995

In [124]:
#Copying the movie dataframe into a new one since we won't need to use the genre information in our first case.
moviesWithGenres_df = movies_df.copy()

#For every row in the dataframe, iterate through the list of genres and place a 1 into the corresponding column
for index, row in movies_df.iterrows():
    for genre in row['genres']:
        moviesWithGenres_df.at[index, 
                                     genre] = int(1)
       
#Filling in the NaN values with 0 to show that a movie doesn't have that column's genre
moviesWithGenres_df = moviesWithGenres_df.fillna(0)
#moviesWithGenres_df.head(5)
display(moviesWithGenres_df)

movieId                        title  \
0            1                    Toy Story   
1            2                      Jumanji   
2            3             Grumpier Old Men   
3            4            Waiting to Exhale   
4            5  Father of the Bride Part II   
...        ...                          ...   
34203   151697                   Grand Slam   
34204   151701                   Bloodmoney   
34205   151703         The Butterfly Circus   
34206   151709                         Zero   
34207   151711        The 2000 Year Old Man   

                                                  genres  year  Adventure  \
0      [Adventure, Animation, Children, Comedy, Fantasy]  1995        1.0   
1                         [Adventure, Children, Fantasy]  1995        1.0   
2                                      [Comedy, Romance]  1995        0.0   
3                               [Comedy, Drama, Romance]  1995        0.0   
4                                               [Comedy]  1995        0.0   
...                                                  ...   ...        ...   
34203                                         [Thriller]  1967        0.0   
34204                               [(no genres listed)]  2010        0.0   
34205                                            [Drama]  2009        0.0   
34206                                    [Drama, Sci-Fi]  2015        0.0   
34207                               [(no genres listed)]  1975        0.0   

       Animation  Children  Comedy  Fantasy  Romance  ...  Horror  Mystery  \
0            1.0       1.0     1.0      1.0      0.0  ...     0.0      0.0   
1            0.0       1.0     0.0      1.0      0.0  ...     0.0      0.0   
2            0.0       0.0     1.0      0.0      1.0  ...     0.0      0.0   
3            0.0       0.0     1.0      0.0      1.0  ...     0.0      0.0   
4            0.0       0.0     1.0      0.0      0.0  ...     0.0      0.0   
...          ...       ...     ...      ...      ...  ...     ...      ...   
34203        0.0       0.0     0.0      0.0      0.0  ...     0.0      0.0   
34204        0.0       0.0     0.0      0.0      0.0  ...     0.0      0.0   
34205        0.0       0.0     0.0      0.0      0.0  ...     0.0      0.0   
34206        0.0       0.0     0.0      0.0      0.0  ...     0.0      0.0   
34207        0.0       0.0     0.0      0.0      0.0  ...     0.0      0.0   

       Sci-Fi  IMAX  Documentary  War  Musical  Western  Film-Noir  \
0         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
1         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
2         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
3         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
4         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
...       ...   ...          ...  ...      ...      ...        ...   
34203     0.0   0.0          0.0  0.0      0.0      0.0        0.0   
34204     0.0   0.0          0.0  0.0      0.0      0.0        0.0   
34205     0.0   0.0          0.0  0.0      0.0      0.0        0.0   
34206     1.0   0.0          0.0  0.0      0.0      0.0        0.0   
34207     0.0   0.0          0.0  0.0      0.0      0.0        0.0   

       (no genres listed)  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     0.0  
...                   ...  
34203                 0.0  
34204                 1.0  
34205                 0.0  
34206                 0.0  
34207                 1.0  

[34208 rows x 24 columns]

In [125]:
#ratings_df.head()
display(ratings_df)

userId  movieId  rating
0              1      169     2.5
1              1     2471     3.0
2              1    48516     5.0
3              2     2571     3.5
4              2   109487     4.0
...          ...      ...     ...
22884372  247753    49530     5.0
22884373  247753    69481     3.0
22884374  247753    74458     4.0
22884375  247753    76093     5.0
22884376  247753   130636     0.5

[22884377 rows x 3 columns]

In [129]:
#Drop removes a specified row or column from a dataframe
#ratings_df = ratings_df.drop('timestamp', 1)
ratings_df.head()

userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

In [130]:
userInput = [
            {'title':'Breakfast Club, The', 'rating':5},
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
inputMovies = pd.DataFrame(userInput)
print(inputMovies.shape)

(5, 2)


In [131]:
#Filtering out the movies by title
# no iteration done it matches the title in one shot

inputId = movies_df[movies_df['title'].isin(inputMovies['title'].tolist())]
#Then merging it so we can get the movieId. It's implicitly merging it by title.
inputMovies = pd.merge(inputId, inputMovies)
#Dropping information we won't use from the input dataframe
inputMovies = inputMovies.drop('genres', 1).drop('year', 1)
#Final input dataframe
#If a movie you added in above isn't here, then it might not be in the original 
#dataframe or it might spelled differently, please check capitalisation.
inputMovies
print(inputId)

      movieId                title  \
0           1            Toy Story   
1           2              Jumanji   
293       296         Pulp Fiction   
1246     1274                Akira   
1885     1968  Breakfast Club, The   

                                                 genres  year  
0     [Adventure, Animation, Children, Comedy, Fantasy]  1995  
1                        [Adventure, Children, Fantasy]  1995  
293                    [Comedy, Crime, Drama, Thriller]  1994  
1246             [Action, Adventure, Animation, Sci-Fi]  1988  
1885                                    [Comedy, Drama]  1985  


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  


In [180]:
#Filtering out the movies from the input
userMovies = moviesWithGenres_df[moviesWithGenres_df['movieId'].isin(inputMovies['movieId'].tolist())]
userMovies

movieId                title  \
0           1            Toy Story   
1           2              Jumanji   
293       296         Pulp Fiction   
1246     1274                Akira   
1885     1968  Breakfast Club, The   

                                                 genres  year  Adventure  \
0     [Adventure, Animation, Children, Comedy, Fantasy]  1995        1.0   
1                        [Adventure, Children, Fantasy]  1995        1.0   
293                    [Comedy, Crime, Drama, Thriller]  1994        0.0   
1246             [Action, Adventure, Animation, Sci-Fi]  1988        1.0   
1885                                    [Comedy, Drama]  1985        0.0   

      Animation  Children  Comedy  Fantasy  Romance  ...  Horror  Mystery  \
0           1.0       1.0     1.0      1.0      0.0  ...     0.0      0.0   
1           0.0       1.0     0.0      1.0      0.0  ...     0.0      0.0   
293         0.0       0.0     1.0      0.0      0.0  ...     0.0      0.0   
1246        1.0       0.0     0.0      0.0      0.0  ...     0.0      0.0   
1885        0.0       0.0     1.0      0.0      0.0  ...     0.0      0.0   

      Sci-Fi  IMAX  Documentary  War  Musical  Western  Film-Noir  \
0        0.0   0.0          0.0  0.0      0.0      0.0        0.0   
1        0.0   0.0          0.0  0.0      0.0      0.0        0.0   
293      0.0   0.0          0.0  0.0      0.0      0.0        0.0   
1246     1.0   0.0          0.0  0.0      0.0      0.0        0.0   
1885     0.0   0.0          0.0  0.0      0.0      0.0        0.0   

      (no genres listed)  
0                    0.0  
1                    0.0  
293                  0.0  
1246                 0.0  
1885                 0.0  

[5 rows x 24 columns]

In [ ]:
userMovies

In [134]:
X = np.asanyarray(inputMovies[['rating']])
x= X.reshape(1,5)
x


array([[3.5, 2. , 5. , 4.5, 5. ]])

In [135]:
d2f = userMovies.drop(['movieId','title','genres','year'],axis=1)

matrix=d2f.to_numpy()

matrix

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [136]:
weighmatrix = np.matmul(x,matrix);

weighmatrix



array([[10. ,  8. ,  5.5, 13.5,  5.5,  0. , 10. ,  4.5,  5. ,  5. ,  0. ,
         0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [137]:
summ = np.sum(weighmatrix)

summ

71.5

In [182]:
mainmatrix = weighmatrix/summ

mainmatrix



array([[0.13986014, 0.11188811, 0.07692308, 0.18881119, 0.07692308,
        0.        , 0.13986014, 0.06293706, 0.06993007, 0.06993007,
        0.        , 0.        , 0.06293706, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [160]:
dff2 = moviesWithGenres_df.copy()

dff2 = dff2[~dff2.isin(userMovies)].dropna()

dff1 = dff2.drop(['movieId','title','genres','year'],axis=1)

dff1

Adventure  Animation  Children  Comedy  Fantasy  Romance  Drama  \
2            0.0        0.0       0.0     1.0      0.0      1.0    0.0   
3            0.0        0.0       0.0     1.0      0.0      1.0    1.0   
4            0.0        0.0       0.0     1.0      0.0      0.0    0.0   
5            0.0        0.0       0.0     0.0      0.0      0.0    0.0   
6            0.0        0.0       0.0     1.0      0.0      1.0    0.0   
...          ...        ...       ...     ...      ...      ...    ...   
34203        0.0        0.0       0.0     0.0      0.0      0.0    0.0   
34204        0.0        0.0       0.0     0.0      0.0      0.0    0.0   
34205        0.0        0.0       0.0     0.0      0.0      0.0    1.0   
34206        0.0        0.0       0.0     0.0      0.0      0.0    1.0   
34207        0.0        0.0       0.0     0.0      0.0      0.0    0.0   

       Action  Crime  Thriller  Horror  Mystery  Sci-Fi  IMAX  Documentary  \
2         0.0    0.0       0.0     0.0      0.0     0.0   0.0          0.0   
3         0.0    0.0       0.0     0.0      0.0     0.0   0.0          0.0   
4         0.0    0.0       0.0     0.0      0.0     0.0   0.0          0.0   
5         1.0    1.0       1.0     0.0      0.0     0.0   0.0          0.0   
6         0.0    0.0       0.0     0.0      0.0     0.0   0.0          0.0   
...       ...    ...       ...     ...      ...     ...   ...          ...   
34203     0.0    0.0       1.0     0.0      0.0     0.0   0.0          0.0   
34204     0.0    0.0       0.0     0.0      0.0     0.0   0.0          0.0   
34205     0.0    0.0       0.0     0.0      0.0     0.0   0.0          0.0   
34206     0.0    0.0       0.0     0.0      0.0     1.0   0.0          0.0   
34207     0.0    0.0       0.0     0.0      0.0     0.0   0.0          0.0   

       War  Musical  Western  Film-Noir  (no genres listed)  
2      0.0      0.0      0.0        0.0                 0.0  
3      0.0      0.0      0.0        0.0                 0.0  
4      0.0      0.0      0.0        0.0                 0.0  
5      0.0      0.0      0.0        0.0                 0.0  
6      0.0      0.0      0.0        0.0                 0.0  
...    ...      ...      ...        ...                 ...  
34203  0.0      0.0      0.0        0.0                 0.0  
34204  0.0      0.0      0.0        0.0                 1.0  
34205  0.0      0.0      0.0        0.0                 0.0  
34206  0.0      0.0      0.0        0.0                 0.0  
34207  0.0      0.0      0.0        0.0                 1.0  

[34203 rows x 20 columns]

In [161]:
datamatrix = dff1.to_numpy()

datamatrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [162]:
datamatrix.shape

(34203, 20)

In [163]:
mainmatrix = mainmatrix.reshape(20,1)

In [145]:
finalmatrix = np.matmul(datamatrix,mainmatrix)

finalmatrix[0:10]

array([[0.18881119],
       [0.32867133],
       [0.18881119],
       [0.2027972 ],
       [0.18881119],
       [0.21678322],
       [0.06293706],
       [0.27272727],
       [0.32867133],
       [0.18881119]])

In [165]:
final1matrix = finalmatrix*5

final1matrix[0:10]

array([[0.94405594],
       [1.64335664],
       [0.94405594],
       [1.01398601],
       [0.94405594],
       [1.08391608],
       [0.31468531],
       [1.36363636],
       [1.64335664],
       [0.94405594]])

In [166]:
final1matrix=np.round(final1matrix,2)

final1matrix[0:10]

array([[0.94],
       [1.64],
       [0.94],
       [1.01],
       [0.94],
       [1.08],
       [0.31],
       [1.36],
       [1.64],
       [0.94]])

In [167]:
max(final1matrix)

array([3.74])

In [168]:
dff2['Ratings']=final1matrix

In [169]:
dff2

movieId                        title                     genres  year  \
2           3.0             Grumpier Old Men          [Comedy, Romance]  1995   
3           4.0            Waiting to Exhale   [Comedy, Drama, Romance]  1995   
4           5.0  Father of the Bride Part II                   [Comedy]  1995   
5           6.0                         Heat  [Action, Crime, Thriller]  1995   
6           7.0                      Sabrina          [Comedy, Romance]  1995   
...         ...                          ...                        ...   ...   
34203  151697.0                   Grand Slam                 [Thriller]  1967   
34204  151701.0                   Bloodmoney       [(no genres listed)]  2010   
34205  151703.0         The Butterfly Circus                    [Drama]  2009   
34206  151709.0                         Zero            [Drama, Sci-Fi]  2015   
34207  151711.0        The 2000 Year Old Man       [(no genres listed)]  1975   

       Adventure  Animation  Children  Comedy  Fantasy  Romance  ...  Mystery  \
2            0.0        0.0       0.0     1.0      0.0      1.0  ...      0.0   
3            0.0        0.0       0.0     1.0      0.0      1.0  ...      0.0   
4            0.0        0.0       0.0     1.0      0.0      0.0  ...      0.0   
5            0.0        0.0       0.0     0.0      0.0      0.0  ...      0.0   
6            0.0        0.0       0.0     1.0      0.0      1.0  ...      0.0   
...          ...        ...       ...     ...      ...      ...  ...      ...   
34203        0.0        0.0       0.0     0.0      0.0      0.0  ...      0.0   
34204        0.0        0.0       0.0     0.0      0.0      0.0  ...      0.0   
34205        0.0        0.0       0.0     0.0      0.0      0.0  ...      0.0   
34206        0.0        0.0       0.0     0.0      0.0      0.0  ...      0.0   
34207        0.0        0.0       0.0     0.0      0.0      0.0  ...      0.0   

       Sci-Fi  IMAX  Documentary  War  Musical  Western  Film-Noir  \
2         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
3         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
4         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
5         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
6         0.0   0.0          0.0  0.0      0.0      0.0        0.0   
...       ...   ...          ...  ...      ...      ...        ...   
34203     0.0   0.0          0.0  0.0      0.0      0.0        0.0   
34204     0.0   0.0          0.0  0.0      0.0      0.0        0.0   
34205     0.0   0.0          0.0  0.0      0.0      0.0        0.0   
34206     1.0   0.0          0.0  0.0      0.0      0.0        0.0   
34207     0.0   0.0          0.0  0.0      0.0      0.0        0.0   

       (no genres listed)  Ratings  
2                     0.0     0.94  
3                     0.0     1.64  
4                     0.0     0.94  
5                     0.0     1.01  
6                     0.0     0.94  
...                   ...      ...  
34203                 0.0     0.35  
34204                 1.0     0.00  
34205                 0.0     0.70  
34206                 0.0     1.01  
34207                 1.0     0.00  

[34203 rows x 25 columns]

This is the Recommanded Movies that the recommander will give to the User

In [190]:
recommand = dff2.loc[dff2['Ratings']>3.2]

recommand2 = recommand[['movieId','title','year']]

print("THE MOVIES RECOMMANDED BY THE RECOMMANDER IS .........\n\nTHESE ARE THE MOVIES HAVING RATING ABOVE 3 OUT OF 5\n\n")

recommand2

THE MOVIES RECOMMANDED BY THE RECOMMANDER IS .........

THESE ARE THE MOVIES HAVING RATING ABOVE 3 OUT OF 5




movieId                                              title  year
664       673.0                                          Space Jam  1996
1824     1907.0                                              Mulan  1998
2902     2987.0                           Who Framed Roger Rabbit?  1988
4625     4719.0                                      Osmosis Jones  2001
4923     5018.0                                           Motorama  1991
6793     6902.0                                      Interstate 60  2002
8605    26093.0         Wonderful World of the Brothers Grimm, The  1962
8783    26340.0  Twelve Tasks of Asterix, The (Les douze travau...  1976
9296    27344.0  Revolutionary Girl Utena: Adolescence of Utena...  1999
9825    32031.0                                             Robots  2005
10575   40339.0                                     Chicken Little  2005
11716   51632.0                            Atlantis: Milo's Return  2003
11751   51939.0                TMNT (Teenage Mutant Ninja Turtles)  2007
11785   52287.0                                 Meet the Robinsons  2007
11806   52462.0  Aqua Teen Hunger Force Colon Movie Film for Th...  2007
13109   62956.0                            Futurama: Bender's Game  2008
13250   64645.0                                  The Wrecking Crew  1968
15001   75408.0  Lupin III: Sweet Lost Night (Rupan Sansei: Swe...  2008
15073   76153.0  Lupin III: First Contact (Rupan Sansei: Faasut...  2002
16055   81132.0                                             Rubber  2010
16884   85261.0                                    Mars Needs Moms  2011
18312   91335.0                                      Gruffalo, The  2009
22145  106240.0                                         Free Birds  2013
22778  108540.0           Ernest & Célestine (Ernest et Célestine)  2012
22881  108932.0                                     The Lego Movie  2014
25218  117646.0                     Dragonheart 2: A New Beginning  2000
26442  122787.0                                       The 39 Steps  1959
28220  130520.0                                               Home  2015
32854  146305.0                             Princes and Princesses  2000
33509  148775.0                Wizards of Waverly Place: The Movie  2009